//
// Created by Aleksandra Generowicz on 27/12/2020.
//
#include <string>

using namespace std;
int const DEFAULT_SIZE = 5;
int const MATRIX_CORRECT = 0;
int const MATRIX_INCORRECT_SIZE_ERROR_CURRENT_MATRIX_NOT_CHANGE = 1;
int const MATRIX_INCORRECT_SIZE_ERROR_DEFAULT_MATRIX_RETURNED = 2;
int const MATRIX_INCORRECT_FILE_READING_ERROR = 3;
int const MATRIX_INCORRECT_GET_VALUE_ERROR = 4;
int const MATRIX_INCORRECT_SET_VALUE_ERROR = 5;
int const MATRIX_INCORRECT_CURRENT_NOT_EXIST_ERROR_DEFAULT_MATRIX_RETURNED = 6;
int const MATRIX_INCORRECT_OTHER_NOT_EXIST_ERROR_CURRENT_MATRIX_RETURNED = 7;
int const MATRIX_INCORRECT_DIMENSION_ERROR = 8;
int const MATRIX_INCORRECT_SIZE_VECTOR_ERROR = 9;
int const MATRIX_INCORRECT_SIZE_FORMAT_COMPLETE_WITH_DEFAULT_VALUE = 10;
int const MATRIX_INCORRECT_VALUE_FORMAT_COMPLETE_WITH_DEFAULT_VALUE = 11;
int const MATRIX_INCORRECT_SIZE_ERROR = 12;
int const MATRIX_INCORRECT_CURRENT_NOT_EXIST_ERROR = 13;
int const MATRIX_INCORRECT_OTHER_NOT_EXIST_ERROR = 14;
string const MATRIX_EXCEPTION_INVALID_DATA = "Incorrect data.";